server.port=8091
logging.level.web = debug

spring.ai.openai.base-url=https://api.gapgpt.app
spring.ai.openai.api-key=sk-bOvDvb9zqQ7xKH1dsIJX9rUoCUeSWtvIiMPh3zJvZzL5Nb2y

spring.ai.openai.chat.options.model=gapgpt-qwen-3.5

spring.ai.openai.chat.options.temperature=0.9
spring.ai.openai.chat.options.max-tokens=500

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://130.185.121.173:8081/realms/project-z
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://130.185.121.173:8081/realms/project-z/protocol/openid-connect/certs
jwt.auth.converter.resource-id: orchestrator-resource
jwt.auth.converter.principle-attribute: preferred_username